<a href="https://colab.research.google.com/github/BusraCevik/SignLanguageRecognition/blob/main/SLLinear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Gerekli kütüphaneleri yükleme
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from google.colab import files
import io
import zipfile

# Veri setini yükleme
uploaded = files.upload()

# Yüklenen dosyaların isimlerini yazdırma
print(uploaded.keys())

# Yüklenen zip dosyasını açma
for filename in uploaded.keys():
    if filename.endswith('.zip'):
        with zipfile.ZipFile(io.BytesIO(uploaded[filename]), 'r') as zip_ref:
            zip_ref.extractall()

# Zip içerisindeki dosya adını kontrol etme ve veri setini yükleme
extracted_files = zip_ref.namelist()
print(extracted_files)

# Varsayalım ki zip içinde 'sign_mnist_train/sign_mnist_train.csv' adında bir dosya var
df = pd.read_csv('sign_mnist_train/sign_mnist_train.csv')  # Dosya adını doğru şekilde değiştirin

# Veri setini keşfetme
print(df.head())
print(df.info())
print(df.describe())

# Veri ön işleme
X = df.drop('label', axis=1)  # 'label' hedef değişkenin adını veri setinizdeki isimle değiştirin
y = df['label']

# Veriyi eğitim ve test setlerine ayırma
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


Saving SignLanguage.zip to SignLanguage.zip
dict_keys(['SignLanguage.zip'])
['amer_sign2.png', 'amer_sign3.png', 'american_sign_language.PNG', 'sign_mnist_test.csv', 'sign_mnist_test/sign_mnist_test.csv', 'sign_mnist_train.csv', 'sign_mnist_train/sign_mnist_train.csv']
   label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      3     107     118     127     134     139     143     146     150   
1      6     155     157     156     156     156     157     156     158   
2      2     187     188     188     187     187     186     187     188   
3      2     211     211     212     212     211     210     211     210   
4     13     164     167     170     172     176     179     180     184   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0     153  ...       207       207       207       207       206       206   
1     158  ...        69       149       128        87        94       163   
2     187  ...       202       201     

In [ ]:
# Lineer Regresyon modeli oluşturma ve eğitme
lr = LinearRegression()
lr.fit(X_train, y_train)

# Modeli değerlendirme
y_pred_lr = lr.predict(X_test)

# Tahminleri sınıflara ayırma (en yakın tamsayıya yuvarlama)
y_pred_lr = np.round(y_pred_lr).astype(int)

# Doğruluğu hesaplama
accuracy_lr = accuracy_score(y_test, y_pred_lr)
print(f"Linear Regression Accuracy: {accuracy_lr:.2f}")

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_lr))

print("Classification Report:")
print(classification_report(y_test, y_pred_lr))


Linear Regression Accuracy: 0.10
Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification Report:
              precision    recall  f1-score   support

          -8       0.00      0.00      0.00         0
          -7       0.00      0.00      0.00         0
          -6       0.00      0.00      0.00         0
          -5       0.00      0.00      0.00         0
          -4       0.00      0.00      0.00         0
          -3       0.00      0.00      0.00         0
          -2       0.00      0.00      0.00         0
          -1       0.00      0.00      0.00         0
           0       0.31      0.07      0.11       221
           1       0.11      0.04      0.06       188
           2       0.20      0.08      0.12       220
           3       0.12      0.06      0.08       256
           4       0.14      0.12      0.13       202
           5       0.10      0.10      0.10      

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
